try:
    raise Exception()
except:
    print 'yeah'
